language: generic 

sudo: required

services:
  - docker 


before_install:
  - docker build -t prashantwalunj999/docker_react .


Script:
  - docker run prashantwalunj999/docker_react -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-323150525394Info' 
  bucket_path: 'docker-react'

  on:
    branch: master

  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'

