language: generic 

sudo: required

services:
  - docker 


before_install:
  - docker build -t prashantwalunj999/docker_react -f Dockerfile.dev .


Script:
  - docker run prashantwalunj999/docker_react npm run test -- --coverage

