FROM node:12-alpine

WORKDIR /app

COPY package.json/ .
RUN npm install

COPY . . 

CMD ["npm", "run", "start"]


#Build image
# docker build -t react_app -f Dockerfile.dev .

#Run App
# docker run -it -p 3000:3000 react_app